# Generated by Django 3.2.9 on 2021-12-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0002_auto_20211203_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='maker_coefficient',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='maker_fee_rate',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='taker_coefficient',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='taker_fee_rate',
        ),
    ]
