# Generated by Django 3.2.9 on 2021-12-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0003_auto_20211203_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeKines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('open', models.FloatField()),
                ('closing', models.FloatField()),
                ('highest', models.FloatField()),
                ('lowest', models.FloatField()),
                ('volume', models.FloatField()),
                ('amount', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickers.ticker')),
            ],
            options={
                'unique_together': {('ticker', 'sequence')},
            },
        ),
    ]
