# Generated by Django 3.2.9 on 2021-12-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0004_tradekines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradeKines',
            new_name='TradeKlines',
        ),
    ]
