# Generated by Django 3.2.9 on 2021-12-04 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0005_rename_tradekines_tradeklines'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookUpScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='LookupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickers.lookupscheduletype')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickers.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='LookupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('datum_count', models.IntegerField()),
                ('lookup_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickers.lookupschedule')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickers.ticker')),
            ],
        ),
    ]
