# Generated by Django 3.2.9 on 2021-12-04 11:48

from django.db import migrations


SCHEDULES = [
    "1min",
    "3min",
    "5min",
    "15min",
    "30min",
    "1hour",
    "2hour",
    "4hour",
    "6hour",
    "8hour",
    "12hour",
    "1day",
    "1week",
]


def add_default_schedules(apps, schema_editor):
    LookUpScheduleType = apps.get_model("tickers", "LookUpScheduleType")
    for schedule in SCHEDULES:
        LookUpScheduleType.objects.get_or_create(value=schedule)


class Migration(migrations.Migration):

    dependencies = [
        ("tickers", "0008_auto_20211204_1136"),
    ]

    operations = [
        migrations.RunPython(add_default_schedules),
    ]
