# Generated by Django 3.2.9 on 2021-12-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0009_add_schedules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeklines',
            old_name='closing',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='tradeklines',
            old_name='highest',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='tradeklines',
            old_name='lowest',
            new_name='low',
        ),
        migrations.AlterUniqueTogether(
            name='lookupschedule',
            unique_together={('schedule', 'ticker')},
        ),
        migrations.AlterUniqueTogether(
            name='tradeklines',
            unique_together={('ticker', 'start', 'end')},
        ),
    ]
