# Generated by Django 3.2.9 on 2021-12-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0011_alter_lookupevent_datum_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeklines',
            name='atr',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
